/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PlanRouteImport } from './app/plan'
import { Route as HealthRouteImport } from './app/health'
import { Route as IndexRouteImport } from './app/index'
import { Route as SightingsSightingIdRouteImport } from './app/sightings/$sightingId'

const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SightingsSightingIdRoute = SightingsSightingIdRouteImport.update({
  id: '/sightings/$sightingId',
  path: '/sightings/$sightingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plan': typeof PlanRoute
  '/sightings/$sightingId': typeof SightingsSightingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plan': typeof PlanRoute
  '/sightings/$sightingId': typeof SightingsSightingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plan': typeof PlanRoute
  '/sightings/$sightingId': typeof SightingsSightingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/health' | '/plan' | '/sightings/$sightingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/plan' | '/sightings/$sightingId'
  id: '__root__' | '/' | '/health' | '/plan' | '/sightings/$sightingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  PlanRoute: typeof PlanRoute
  SightingsSightingIdRoute: typeof SightingsSightingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sightings/$sightingId': {
      id: '/sightings/$sightingId'
      path: '/sightings/$sightingId'
      fullPath: '/sightings/$sightingId'
      preLoaderRoute: typeof SightingsSightingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  PlanRoute: PlanRoute,
  SightingsSightingIdRoute: SightingsSightingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
